### ISSUE TITLE
E       TypeError: __init__() got an unexpected keyword argument 'prov_class'

### ISSUE THREAD

**Issue by jaryn** [RedHatQE/widgetastic.core#110]
I am getting this problem with HEAD on 3ec95dd518d28b800a3f2c99fc8bcf8f7ca5c7ee
```
>       network_provider = collection.all()[0]

cfme/tests/networks/test_sdn_inventory_collection.py:132: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
cfme/networks/provider/__init__.py:294: in all
    provider=self.filters.get('provider')))
cfme/modeling/base.py:119: in instantiate
    return self.ENTITY.from_collection(self, *args, **kwargs)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

cls = <class 'cfme.networks.provider.NetworkProvider'>
collection = NetworkProviderCollection(filters={'provider': AzureProvider(endpoints={'defau...d-8922-c9b8e2c3f100', subscription_id='c9e72ccc-b20e-48bd-a0c8-879c6dbcbfbb')})
k = ()
kw = {'name': 'azure Network Manager', 'prov_class': <class 'cfme.networks.provider.NetworkProvider'>, 'provider': AzurePro...cloud.provider.azure.AzureEndpoint o...0ed-8922-c9b8e2c3f100', subscription_id='c9e72ccc-b20e-48bd-a0c8-879c6dbcbfbb')}

    @classmethod
    def from_collection(cls, collection, *k, **kw):
>       return cls(collection, *k, **kw)
E       TypeError: __init__() got an unexpected keyword argument 'prov_class'
```

I found out it is introduced with 0284b75a90.
